### ISSUE TITLE
very good analysis

### ISSUE THREAD

**Issue by VB10** [OzgurBoruzanci/Gidelim_App#26]
https://github.com/OzgurBoruzanci/Gidelim_App/blob/faa660d5a430702887d6f0d503d55aaa8625a422/bootcamp91/pubspec.yaml#L28

paketi güncellersek bir çok hata veya wanring gelecektir onları çözeli

**Comment by ozcanbayram** [comment]
[Gidelim_App/bootcamp91/pubspec.yaml](https://github.com/OzgurBoruzanci/Gidelim_App/blob/faa660d5a430702887d6f0d503d55aaa8625a422/bootcamp91/pubspec.yaml#L28)

>  flutter_lints: ^4.0.0

Paketi güncelledim.
